### ISSUE TITLE
Create models mirroring existing db views

### ISSUE THREAD

**Issue by webknjaz** [wk-tech/crm-smsfly#11]
https://blog.rescale.com/using-database-views-in-django-orm/
http://stackoverflow.com/questions/507795/can-i-use-a-database-view-as-a-model-in-django

**Comment by bluebirrrrd** [comment]
Use `inspectdb` to do this: https://docs.djangoproject.com/en/1.9/howto/legacy-databases/

**Comment by webknjaz** [comment]
http://stackoverflow.com/a/34635951/595220
